#:schema node_modules/wrangler/config-schema.json
name = "clerk-multitenant-cf-workers-example"
main = "./server.ts"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"


[vars]
CLERK_SIGN_IN_URL="/sign-in"
CLERK_SIGN_UP_URL="/sign-up"
CLERK_SIGN_IN_FALLBACK_URL="/"
CLERK_SIGN_UP_FALLBACK_URL="/"
CLERK_AFTER_SIGN_UP_URL="/app"
CLERK_AFTER_SIGN_IN_URL="/app"